### ISSUE TITLE
Not able to download Penn Treebank data

### ISSUE THREAD

**Issue by songyuzhou324** [zihangdai/mos#1]
Hi, Zihang

It seems that the original link for downloading Penn Treebank data no longer exists. Could you please update this and let me know where I can download the same data to replicate your experiment ?

Thanks,
Yuzhou

**Comment by hardik2396** [comment]
Hello,
You can download PTB from here: 
https://github.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/tree/master/data

**Comment by hunan-rostomyan** [comment]
PTB licensing seems to have changed. This might be informative: https://catalog.ldc.upenn.edu/ldc99t42.

**Comment by songyuzhou324** [comment]
OK, thanks!
