### ISSUE TITLE
What is creators GPU hardware and speed?

### ISSUE THREAD

**Issue by cbrew** [zihangdai/mos#2]
Which GPU does the first recommended command line run well on? On an Nvidia 1050ti (4Gb of GPU memory) it exhausts GPU memory with a batch size of 12, but runs with a batch size of 6. With that setting, I get order of 300ms per batch. Ubuntu Linux 16.04 on a cheap used Dell 7500 with two 6 core Xeons, if it matters.

**Comment by kimiyoung** [comment]
You would need GPUs with 12GB memory to run these experiments with the given command line.
