### ISSUE TITLE
questions about bptt  

### ISSUE THREAD

**Issue by kscp123** [zihangdai/mos#5]
Hi author,I'm a newbie on NLP. I don't understand the use of "bptt"(args.bptt = 70) and some expressions related to it,such as followings:

bptt = args.bptt if np.random.random() < 0.95 else args.bptt / 2.
seq_len = max(5, int(np.random.normal(bptt, 5)))
seq_len = min(seq_len, args.bptt + args.max_seq_len_delta)
optimizer.param_groups[0]['lr'] = lr2 * seq_len / args.bptt

To my understanding, seq_len is the time-step of RNN. So what's the relationship between "bptt" and "seq_len"? Could you please help to explain some of it? Thanks

**Comment by zihangdai** [comment]
See https://arxiv.org/pdf/1708.02182.pdf section 4.1.

**Comment by kscp123** [comment]
It helps a lot, many thanks!
